// AUTO-GENERATED from data/datacenters.csv by build_data.py — do not edit by hand.
window.DATACENTERS = [
  {
    "id": "tn-chennai-stt-ambattur-cda",
    "name": "STT Chennai Ambattur Campus",
    "operator": "STT GDC India",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.162,
    "status": "operational",
    "it_load_mw": 40.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Ambattur campus ~130MW total potential; houses STT Chennai 1-4",
    "source": "https://www.sttelemediagdc.com/newsroom/stt-gdc-india-strengthens-its-market-presence-chennai-multi-campus-expansion-and-inr-4200"
  },
  {
    "id": "tn-chennai-stt-siruseri",
    "name": "STT Chennai Siruseri Campus",
    "operator": "STT GDC India",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 12.823,
    "longitude": 80.218,
    "status": "operational",
    "it_load_mw": 7.2,
    "commissioned_year": 2026,
    "water_stressed": true,
    "notes": "45MW AI-ready campus; first phase 7.2MW live (STT Chennai 7)",
    "source": "https://www.crnasia.com/india/news/2026/stt-gdc-launches-45-mw-ai-ready-chennai-facility-commits-4-200-crore-investment"
  },
  {
    "id": "ka-bengaluru-stt-blr1",
    "name": "STT Bangalore 1",
    "operator": "STT GDC India",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "ka-bengaluru-stt-blr2",
    "name": "STT Bangalore 2",
    "operator": "STT GDC India",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "ka-bengaluru-stt-blr3",
    "name": "STT Bangalore 3",
    "operator": "STT GDC India",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "dl-noida-stt-delhi1",
    "name": "STT Delhi 1",
    "operator": "STT GDC India",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "dl-noida-stt-delhi2",
    "name": "STT Delhi 2",
    "operator": "STT GDC India",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "dl-noida-stt-delhi3",
    "name": "STT Delhi 3",
    "operator": "STT GDC India",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "up-noida-stt-noida1",
    "name": "STT Noida 1",
    "operator": "STT GDC India",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "up-noida-stt-noida2",
    "name": "STT Noida 2",
    "operator": "STT GDC India",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "rj-jaipur-stt-jaipur1",
    "name": "STT Jaipur 1",
    "operator": "STT GDC India",
    "city": "Jaipur",
    "state": "Rajasthan",
    "latitude": 26.9124,
    "longitude": 75.7873,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "wb-kolkata-stt-kol1",
    "name": "STT Kolkata 1",
    "operator": "STT GDC India",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "wb-kolkata-stt-kol2",
    "name": "STT Kolkata 2",
    "operator": "STT GDC India",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-mumbai-stt-mum1",
    "name": "STT Mumbai 1",
    "operator": "STT GDC India",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-mumbai-stt-mum2",
    "name": "STT Mumbai 2",
    "operator": "STT GDC India",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-mumbai-stt-mum3",
    "name": "STT Mumbai 3",
    "operator": "STT GDC India",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-mumbai-stt-mum4",
    "name": "STT Mumbai 4",
    "operator": "STT GDC India",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-navimumbai-stt-nav1",
    "name": "STT Navi Mumbai 1",
    "operator": "STT GDC India",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1136,
    "longitude": 73.0169,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "MIDC Mahape campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-navimumbai-stt-nav2",
    "name": "STT Navi Mumbai 2",
    "operator": "STT GDC India",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1136,
    "longitude": 73.0169,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "MIDC Mahape campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-navimumbai-stt-nav3",
    "name": "STT Navi Mumbai 3",
    "operator": "STT GDC India",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1136,
    "longitude": 73.0169,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "MIDC Mahape campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-navimumbai-stt-palava",
    "name": "STT GDC Palava",
    "operator": "STT GDC India",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.15,
    "longitude": 73.12,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Palava campus near Dombivli",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-pune-stt-pune1",
    "name": "STT Pune 1",
    "operator": "STT GDC India",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Five-building Pune campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-pune-stt-pune2",
    "name": "STT Pune 2",
    "operator": "STT GDC India",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Five-building Pune campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-pune-stt-pune3",
    "name": "STT Pune 3",
    "operator": "STT GDC India",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Five-building Pune campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-pune-stt-pune4",
    "name": "STT Pune 4",
    "operator": "STT GDC India",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Five-building Pune campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "mh-pune-stt-pune5",
    "name": "STT Pune 5",
    "operator": "STT GDC India",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Five-building Pune campus",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "gj-gandhinagar-stt-ahmedabad1",
    "name": "STT Ahmedabad DC 1",
    "operator": "STT GDC India",
    "city": "Gandhinagar",
    "state": "Gujarat",
    "latitude": 23.1645,
    "longitude": 72.6838,
    "status": "operational",
    "it_load_mw": 3.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "GIFT City Gandhinagar; ~3MW IT load; LEED Gold",
    "source": "https://www.sttelemediagdc.com/in-en/locations/ahmedabad"
  },
  {
    "id": "tg-hyderabad-stt-hyd1",
    "name": "STT Hyderabad DC 1",
    "operator": "STT GDC India",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.4483,
    "longitude": 78.3915,
    "status": "operational",
    "it_load_mw": 8.0,
    "commissioned_year": 2007,
    "water_stressed": true,
    "notes": "HITEC City Madhapur; TIA-942 Rated-3",
    "source": "https://www.sttelemediagdc.com/in-en/locations"
  },
  {
    "id": "tg-hyderabad-stt-meerkhanpet",
    "name": "STT Hyderabad Meerkhanpet Campus",
    "operator": "STT GDC India",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.15,
    "longitude": 78.4,
    "status": "under_construction",
    "it_load_mw": 100.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Planned ~100MW campus; ~$404m investment",
    "source": "https://www.datacenterdynamics.com/en/news/stt-gdc-to-build-404m-data-center-campus-in-hyderabad-india/"
  },
  {
    "id": "mh-mumbai-ntt-dc5",
    "name": "NTT Mumbai Chandivali DC5",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Chandivali/Andheri campus (ex-Netmagic)",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-dc6",
    "name": "NTT Mumbai Chandivali DC6",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": 19.2,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Andheri (ex-Netmagic)",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-dc7",
    "name": "NTT Mumbai Chandivali DC7",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Chandivali campus",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-dc8",
    "name": "NTT Mumbai Chandivali DC8",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Chandivali campus",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-dc9",
    "name": "NTT Mumbai Chandivali DC9",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Chandivali campus",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-dc10",
    "name": "NTT Mumbai Chandivali DC10",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Chandivali campus",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-vikhroli",
    "name": "NTT Mumbai Vikhroli",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.93,
    "status": "operational",
    "it_load_mw": 2.4,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Vikhroli (ex-Netmagic Mumbai 2)",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-mumbai-ntt-vikhroli4",
    "name": "NTT Mumbai Vikhroli Phase IV",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.93,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Vikhroli campus",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "mh-navimumbai-ntt-nav1a",
    "name": "NTT Navi Mumbai NAV1A",
    "operator": "NTT Global Data Centers",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1136,
    "longitude": 73.0169,
    "status": "operational",
    "it_load_mw": 30.0,
    "commissioned_year": 2022,
    "water_stressed": false,
    "notes": "First building of 2nd hyperscale campus; 5000 racks",
    "source": "https://services.global.ntt/en-us/newsroom/ntt-ltd-launches-new-hyperscale-data-center-park-in-navi-mumbai"
  },
  {
    "id": "mh-navimumbai-ntt-nav2",
    "name": "NTT Navi Mumbai NAV2 Campus",
    "operator": "NTT Global Data Centers",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1136,
    "longitude": 73.0169,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "500MW campus (336MW IT); incl India's largest single-building 50MW DC",
    "source": "https://w.media/ntt-launches-500-mw-dc-campus-in-mumbai/"
  },
  {
    "id": "mh-mumbai-ntt-bse",
    "name": "NTT Mumbai BSE",
    "operator": "NTT Global Data Centers",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.0559,
    "longitude": 72.833,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "BSE building facility",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "ka-bengaluru-ntt-dc2",
    "name": "NTT Bengaluru DC2",
    "operator": "NTT Global Data Centers",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "ex-Netmagic Bangalore",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "ka-bengaluru-ntt-dc3",
    "name": "NTT Bengaluru DC3",
    "operator": "NTT Global Data Centers",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "ka-bengaluru-ntt-dc4",
    "name": "NTT Bengaluru 4 Campus",
    "operator": "NTT Global Data Centers",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "BLR 4A/4B/4C campus",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "tn-chennai-ntt-dc1",
    "name": "NTT Chennai 1",
    "operator": "NTT Global Data Centers",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "operational",
    "it_load_mw": 4.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "1500 sqm IT space; 4MW IT load",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "tn-chennai-ntt-dc2",
    "name": "NTT Chennai 2",
    "operator": "NTT Global Data Centers",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "up-noida-ntt-noida1",
    "name": "NTT Noida 1 (DEL1)",
    "operator": "NTT Global Data Centers",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "ex-Netmagic Delhi/Noida",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "up-noida-ntt-noida2",
    "name": "NTT Noida 2",
    "operator": "NTT Global Data Centers",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Includes Noida 2 Bldg B; seismic dampers",
    "source": "https://services.global.ntt/en-us/newsroom/ntt-expands-india-footprint-with-new-data-center-campus-in-noida"
  },
  {
    "id": "wb-kolkata-ntt-kol1",
    "name": "NTT Kolkata 1 Campus",
    "operator": "NTT Global Data Centers",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "operational",
    "it_load_mw": 40.0,
    "commissioned_year": 2024,
    "water_stressed": false,
    "notes": "Bengal Silicon Valley; 2 buildings, up to 40MW",
    "source": "https://services.global.ntt/en-us/services-and-products/global-data-centers/global-locations/india"
  },
  {
    "id": "tg-hyderabad-ntt-aicluster",
    "name": "NTT Hyderabad AI Data Center Cluster",
    "operator": "NTT Global Data Centers",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "proposed",
    "it_load_mw": 400.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Planned 400MW AI cluster w/ Neysa & Telangana govt; ~$1.2bn",
    "source": "https://www.datacenterdynamics.com/en/news/ntt-plans-data-center-in-hyderabad-india/"
  },
  {
    "id": "tg-hyderabad-ctrls-dc1",
    "name": "CtrlS Hyderabad DC1",
    "operator": "CtrlS",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.4435,
    "longitude": 78.3772,
    "status": "operational",
    "it_load_mw": 4.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "HITEC City Madhapur; first CtrlS facility",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "tg-hyderabad-ctrls-dc2",
    "name": "CtrlS Hyderabad DC2",
    "operator": "CtrlS",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Financial District Gachibowli area",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "tg-hyderabad-ctrls-dc3",
    "name": "CtrlS Hyderabad DC3",
    "operator": "CtrlS",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.4239,
    "longitude": 78.3489,
    "status": "operational",
    "it_load_mw": 13.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Gachibowli; 130k sq ft 13MW IT load",
    "source": "https://www.blackridgeresearch.com/news-releases/ctrls-unveils-its-third-hyperscale-data-center-facility-in-hyderabad-india"
  },
  {
    "id": "tg-hyderabad-ctrls-chandanvelly",
    "name": "CtrlS Chandanvelly Campus",
    "operator": "CtrlS",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.25,
    "longitude": 78.15,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "40-acre park up to 600MW",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "mh-mumbai-ctrls-campus",
    "name": "CtrlS Mumbai Campus",
    "operator": "CtrlS",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.033,
    "longitude": 73.0297,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Mahape campus expanding to 13 buildings",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "tn-chennai-ctrls-dc-park",
    "name": "CtrlS Chennai Datacenter Park",
    "operator": "CtrlS",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "operational",
    "it_load_mw": 72.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "1M sq ft two buildings 72MW IT load",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "up-noida-ctrls-dc",
    "name": "CtrlS Noida DC",
    "operator": "CtrlS",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Rated-4 NCR facility",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "ka-bengaluru-ctrls-dc",
    "name": "CtrlS Bengaluru DC",
    "operator": "CtrlS",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": 12.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "12MW IT load 2000+ racks",
    "source": "https://www.ctrls.com/datacenter-bangalore/"
  },
  {
    "id": "wb-kolkata-ctrls-campus",
    "name": "CtrlS Kolkata Campus",
    "operator": "CtrlS",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "proposed",
    "it_load_mw": 60.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Rs2200cr four-phase 60+MW",
    "source": "https://www.datacenterdynamics.com/en/news/indias-ctrls-datacenters-to-build-data-center-campus-in-kolkata/"
  },
  {
    "id": "br-patna-ctrls-edge",
    "name": "CtrlS Patna Edge DC",
    "operator": "CtrlS",
    "city": "Patna",
    "state": "Bihar",
    "latitude": 25.5941,
    "longitude": 85.1376,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": null,
    "notes": "Edge DC Rs400cr investment",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "up-lucknow-ctrls-edge",
    "name": "CtrlS Lucknow Edge DC",
    "operator": "CtrlS",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "latitude": 26.8467,
    "longitude": 80.9462,
    "status": "operational",
    "it_load_mw": 0.18,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Gomti Nagar edge facility; 49 racks; 2500 sqft",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "gj-ahmedabad-ctrls-edge",
    "name": "CtrlS Ahmedabad Edge DC",
    "operator": "CtrlS",
    "city": "Ahmedabad",
    "state": "Gujarat",
    "latitude": 23.0225,
    "longitude": 72.5714,
    "status": "operational",
    "it_load_mw": 9.2,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Edge DC 800 racks",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "mp-bhopal-ctrls-edge",
    "name": "CtrlS Bhopal Edge DC",
    "operator": "CtrlS",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "latitude": 23.2599,
    "longitude": 77.4126,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": null,
    "notes": "Badwai IT Park 5-acre",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "gj-gandhinagar-ctrls-gift",
    "name": "CtrlS Gandhinagar 1 DC",
    "operator": "CtrlS",
    "city": "Gandhinagar",
    "state": "Gujarat",
    "latitude": 23.1645,
    "longitude": 72.6841,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Tier IV at GIFT City",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "as-guwahati-ctrls-edge",
    "name": "CtrlS Guwahati Edge DC",
    "operator": "CtrlS",
    "city": "Guwahati",
    "state": "Assam",
    "latitude": 26.1445,
    "longitude": 91.7362,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": null,
    "notes": "Rated-4 edge Tech City Park",
    "source": "https://www.ctrls.com/datacenters/"
  },
  {
    "id": "tn-chennai-sify-01-tidel",
    "name": "Sify Chennai 01 Tidel Park",
    "operator": "Sify",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 12.9908,
    "longitude": 80.248,
    "status": "operational",
    "it_load_mw": 3.58,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Tidel Park 800+ racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "tn-chennai-sify-02-siruseri",
    "name": "Sify Chennai 02 Siruseri Campus",
    "operator": "Sify",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 12.823,
    "longitude": 80.227,
    "status": "operational",
    "it_load_mw": 25.92,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "SIPCOT IT Park Siruseri hyperscale",
    "source": "https://www.sifytechnologies.com/data-center/chennai02-data-center/"
  },
  {
    "id": "mh-navimumbai-sify-01-vashi",
    "name": "Sify Mumbai 01 Vashi",
    "operator": "Sify",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.07,
    "longitude": 72.9986,
    "status": "operational",
    "it_load_mw": 0.9,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "India's first commercial DC 375 racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "mh-navimumbai-sify-02-airoli",
    "name": "Sify Mumbai 02 Airoli",
    "operator": "Sify",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1568,
    "longitude": 72.999,
    "status": "operational",
    "it_load_mw": 5.4,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "1345 racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "mh-navimumbai-sify-03-rabale",
    "name": "Sify Mumbai 03 Rabale Campus",
    "operator": "Sify",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.137,
    "longitude": 73.017,
    "status": "operational",
    "it_load_mw": 96.94,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Largest hyperscale campus 12 towers planned",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "up-noida-sify-01",
    "name": "Sify Noida 01",
    "operator": "Sify",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": 11.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "First green DC 2100 racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "up-noida-sify-02",
    "name": "Sify Noida 02 Campus",
    "operator": "Sify",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.506,
    "longitude": 77.4,
    "status": "operational",
    "it_load_mw": 25.92,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Hyperscale 130+MW planned three towers",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "ka-bengaluru-sify-01",
    "name": "Sify Bengaluru 01",
    "operator": "Sify",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.845,
    "longitude": 77.66,
    "status": "operational",
    "it_load_mw": 7.6,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Cyber Park Electronic City 600+ racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "ka-bengaluru-sify-02-aerospace",
    "name": "Sify Bengaluru 02 Aerospace Park",
    "operator": "Sify",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 13.15,
    "longitude": 77.7,
    "status": "under_construction",
    "it_load_mw": 40.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Aerospace Park 40+MW first tower 2025",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "tg-hyderabad-sify-01",
    "name": "Sify Hyderabad 01",
    "operator": "Sify",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.4126,
    "longitude": 78.448,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Banjara Hills 2400 racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "tg-hyderabad-sify-02-fabcity",
    "name": "Sify Hyderabad 02 Fab City Campus",
    "operator": "Sify",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.22,
    "longitude": 78.33,
    "status": "under_construction",
    "it_load_mw": 250.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Fab City up to 250+MW",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "wb-kolkata-sify-01",
    "name": "Sify Kolkata 01",
    "operator": "Sify",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "operational",
    "it_load_mw": 2.2,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "400+ racks",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "ap-visakhapatnam-sify-rushikonda",
    "name": "Sify Visakhapatnam Rushikonda Edge DC",
    "operator": "Sify",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "latitude": 17.78,
    "longitude": 83.38,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "AI Edge DC Meta partnership reported",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "ch-chandigarh-sify",
    "name": "Sify Chandigarh",
    "operator": "Sify",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "latitude": 30.7333,
    "longitude": 76.7794,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": null,
    "notes": "Phase I operational Oct 2025",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "up-lucknow-sify",
    "name": "Sify Lucknow",
    "operator": "Sify",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "latitude": 26.8467,
    "longitude": 80.9462,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Four-phase Phase I Jun 2025",
    "source": "https://www.datacenterdynamics.com/en/news/sify-breaks-ground-on-lucknow-data-center-in-india/"
  },
  {
    "id": "mh-nagpur-sify",
    "name": "Sify Nagpur",
    "operator": "Sify",
    "city": "Nagpur",
    "state": "Maharashtra",
    "latitude": 21.1458,
    "longitude": 79.0882,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Phase I expected 2026",
    "source": "https://www.sifytechnologies.com/data-center/"
  },
  {
    "id": "mh-mumbai-nxtra-mum1",
    "name": "Nxtra Mumbai I (Airoli)",
    "operator": "Nxtra by Airtel",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.033,
    "longitude": 73.0297,
    "status": "operational",
    "it_load_mw": 8.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Airoli ~1100 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "mh-mumbai-nxtra-mum2",
    "name": "Nxtra Mumbai II (Chandivali)",
    "operator": "Nxtra by Airtel",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.109,
    "longitude": 72.892,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Chandivali ~600 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "mh-mumbai-nxtra-mum3",
    "name": "Nxtra Mumbai III",
    "operator": "Nxtra by Airtel",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": null,
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "mh-pune-nxtra-pun1",
    "name": "Nxtra Pune I (Kharadi)",
    "operator": "Nxtra by Airtel",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.551,
    "longitude": 73.947,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Kharadi",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "mh-pune-nxtra-pun2",
    "name": "Nxtra Pune II (Hinjewadi)",
    "operator": "Nxtra by Airtel",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5912,
    "longitude": 73.7389,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Hinjewadi",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "mh-pune-nxtra-pun3",
    "name": "Nxtra Pune III (Hinjewadi)",
    "operator": "Nxtra by Airtel",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5912,
    "longitude": 73.7389,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Hinjewadi 1M sqft campus 12500 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "tn-chennai-nxtra-chn1",
    "name": "Nxtra Chennai I (Santhome)",
    "operator": "Nxtra by Airtel",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.033,
    "longitude": 80.277,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Santhome",
    "source": "https://www.nxtra.in/data-center-chennai"
  },
  {
    "id": "tn-chennai-nxtra-chn2",
    "name": "Nxtra Chennai II (Siruseri)",
    "operator": "Nxtra by Airtel",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 12.823,
    "longitude": 80.221,
    "status": "operational",
    "it_load_mw": 38.0,
    "commissioned_year": 2021,
    "water_stressed": true,
    "notes": "38 MW hyperscale Siruseri",
    "source": "https://www.airtel.in/press-release/11-2021/nxtra-by-airtel-launches-new-38-mw-hyperscale-data-center-in-chennai"
  },
  {
    "id": "tn-chennai-nxtra-chn3",
    "name": "Nxtra Chennai III (Siruseri)",
    "operator": "Nxtra by Airtel",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 12.823,
    "longitude": 80.221,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Siruseri; city total ~46 MW",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "wb-kolkata-nxtra-kol1",
    "name": "Nxtra Kolkata I",
    "operator": "Nxtra by Airtel",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.58,
    "longitude": 88.48,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "New Town Bengal Silicon Valley Rs600cr",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "up-noida-nxtra-ncr1",
    "name": "Nxtra Noida I (Sector 62)",
    "operator": "Nxtra by Airtel",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.628,
    "longitude": 77.364,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Sector 62 ~1200 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "up-noida-nxtra-ncr2",
    "name": "Nxtra Noida II (Sector 81)",
    "operator": "Nxtra by Airtel",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.565,
    "longitude": 77.385,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Sector 81 ~1500 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "up-noida-nxtra-ncr4",
    "name": "Nxtra Noida III",
    "operator": "Nxtra by Airtel",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "hr-manesar-nxtra-ncr3",
    "name": "Nxtra Manesar I",
    "operator": "Nxtra by Airtel",
    "city": "Manesar",
    "state": "Haryana",
    "latitude": 28.3536,
    "longitude": 76.9417,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "IMT Manesar Sector 8 ~1800 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "ka-bengaluru-nxtra-blr1",
    "name": "Nxtra Bengaluru I",
    "operator": "Nxtra by Airtel",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "ka-bengaluru-nxtra-blr2",
    "name": "Nxtra Bengaluru II",
    "operator": "Nxtra by Airtel",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "450000 sqft hyperscale ~5000 racks",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "tg-hyderabad-nxtra-hyd1",
    "name": "Nxtra Hyderabad I",
    "operator": "Nxtra by Airtel",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": null,
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "tg-hyderabad-nxtra-hyd2",
    "name": "Nxtra Hyderabad (200MW campus)",
    "operator": "Nxtra by Airtel",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "proposed",
    "it_load_mw": 200.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "40-acre 200 MW announced",
    "source": "https://www.datacenterdynamics.com/en/news/airtels-nxtra-plans-200mw-hyderabad-data-centers/"
  },
  {
    "id": "od-bhubaneswar-nxtra-bbs1",
    "name": "Nxtra Bhubaneswar I",
    "operator": "Nxtra by Airtel",
    "city": "Bhubaneswar",
    "state": "Odisha",
    "latitude": 20.349,
    "longitude": 85.816,
    "status": "operational",
    "it_load_mw": 1.8,
    "commissioned_year": null,
    "water_stressed": null,
    "notes": "Infocity Avenue Patia",
    "source": "https://www.nxtra.in/"
  },
  {
    "id": "mh-mumbai-ironmountain-mum1",
    "name": "Iron Mountain MUM-1 (ex-Web Werks)",
    "operator": "Iron Mountain / Web Werks",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": 2.3,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Former Web Werks JV; 50000 sqft; 2.3MW",
    "source": "https://www.ironmountain.com/en-in/data-centers/locations/mumbai-data-center"
  },
  {
    "id": "mh-mumbai-ironmountain-mum2",
    "name": "Iron Mountain MUM-2 (ex-Web Werks)",
    "operator": "Iron Mountain / Web Werks",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": 6.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "120000 sqft campus; 6MW",
    "source": "https://www.ironmountain.com/en-in/data-centers/locations/mumbai-data-center"
  },
  {
    "id": "up-noida-ironmountain-ncr1",
    "name": "Iron Mountain NCR-1 (ex-Web Werks)",
    "operator": "Iron Mountain / Web Werks",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": 12.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "69735 sqft; scalable 12MW; Delhi NCR",
    "source": "https://www.ironmountain.com/data-centers/locations/delhi-ncr-data-center"
  },
  {
    "id": "mh-pune-ironmountain-pun1",
    "name": "Iron Mountain PUN-1 (ex-Web Werks)",
    "operator": "Iron Mountain / Web Werks",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": 1.6,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "38000 sqft; 1.6MW; near Pune airport",
    "source": "https://www.ironmountain.com/data-centers/locations/pune-data-center"
  },
  {
    "id": "ka-bengaluru-ironmountain",
    "name": "Iron Mountain Bangalore (ex-Web Werks)",
    "operator": "Iron Mountain / Web Werks",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9698,
    "longitude": 77.75,
    "status": "operational",
    "it_load_mw": 4.1,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Tier III Whitefield facility; 180+ ISPs",
    "source": "https://www.ironmountain.com/en-in/data-centers/locations/mumbai-data-center"
  },
  {
    "id": "tg-hyderabad-ironmountain-hyd1",
    "name": "Iron Mountain Hyderabad (Kondapur)",
    "operator": "Iron Mountain / Web Werks",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.462,
    "longitude": 78.364,
    "status": "operational",
    "it_load_mw": 5.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Kondapur Main Road",
    "source": "https://www.ironmountain.com/data-centers/locations"
  },
  {
    "id": "mh-mumbai-ironmountain-newcampus",
    "name": "Iron Mountain Mumbai 85MW campus",
    "operator": "Iron Mountain / Web Werks",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "under_construction",
    "it_load_mw": 85.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "New 85MW build-to-suit campus",
    "source": "https://www.datacenterdynamics.com/en/news/iron-mountain-breaks-ground-on-85mw-data-center-in-mumbai-india/"
  },
  {
    "id": "tn-chennai-adani-dc1",
    "name": "AdaniConneX Chennai 1",
    "operator": "AdaniConneX",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 12.981,
    "longitude": 80.221,
    "status": "operational",
    "it_load_mw": 33.0,
    "commissioned_year": 2022,
    "water_stressed": true,
    "notes": "SIPCOT IT Park; Phase 1 17MW live Oct 2022 scaling to 33MW",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "tg-hyderabad-adani-dc1",
    "name": "AdaniConneX Hyderabad",
    "operator": "AdaniConneX",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.247,
    "longitude": 78.089,
    "status": "operational",
    "it_load_mw": 100.0,
    "commissioned_year": 2024,
    "water_stressed": true,
    "notes": "Chandanvelly/Pargi Road; 100MW IT load; Phase 1 live Oct 2024",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "up-noida-adani-dc1",
    "name": "AdaniConneX Noida",
    "operator": "AdaniConneX",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.571,
    "longitude": 77.321,
    "status": "operational",
    "it_load_mw": 150.0,
    "commissioned_year": 2025,
    "water_stressed": true,
    "notes": "Delhi-NCR; 150MW IT load; Phase 1 live Jan 2025",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "mh-pune-adani-dc1",
    "name": "AdaniConneX Pune",
    "operator": "AdaniConneX",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "under_construction",
    "it_load_mw": 250.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "250MW IT load; Phase 1 H2 2025",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "mh-navi-mumbai-adani-dc1",
    "name": "AdaniConneX Navi Mumbai",
    "operator": "AdaniConneX",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.033,
    "longitude": 73.0297,
    "status": "under_construction",
    "it_load_mw": 1000.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Up to 1000MW IT load; Dec 2026 onwards",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "ap-visakhapatnam-adani-dc1",
    "name": "AdaniConneX Visakhapatnam",
    "operator": "AdaniConneX",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "latitude": 17.821,
    "longitude": 83.369,
    "status": "under_construction",
    "it_load_mw": 200.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Madhurawada; ~200MW campus; first of three tech zones",
    "source": "https://www.datacenterdynamics.com/en/news/adaniconnex-to-build-200mw-data-center-campus-in-andhra-pradesh-india/"
  },
  {
    "id": "ap-visakhapatnam-adani-google-aihub",
    "name": "Visakhapatnam Google AI Hub (Adani-Google)",
    "operator": "AdaniConneX / Google",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "latitude": 17.821,
    "longitude": 83.369,
    "status": "proposed",
    "it_load_mw": 1000.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Adani-Google JV; 1GW AI campus; USD 15B 2026-2030; Google's largest AI hub outside US",
    "source": "https://www.adani.com/newsroom/media-releases/adani-and-google-partner-to-build-indias-largest-data-centre-campus-in-visakhapatnam"
  },
  {
    "id": "wb-kolkata-adani-dc1",
    "name": "AdaniConneX Kolkata",
    "operator": "AdaniConneX",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Listed under construction",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "ka-bengaluru-adani-dc1",
    "name": "AdaniConneX Bengaluru",
    "operator": "AdaniConneX",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Planned campus",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "od-bhubaneswar-adani-dc1",
    "name": "AdaniConneX Bhubaneswar",
    "operator": "AdaniConneX",
    "city": "Bhubaneswar",
    "state": "Odisha",
    "latitude": 20.2961,
    "longitude": 85.8245,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Planned campus",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "mh-mumbai-adani-dc1",
    "name": "AdaniConneX Mumbai",
    "operator": "AdaniConneX",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Listed operational",
    "source": "https://www.adaniconnex.com/data-centers"
  },
  {
    "id": "mh-navi-mumbai-yotta-nm1",
    "name": "Yotta NM1",
    "operator": "Yotta",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 18.989,
    "longitude": 73.118,
    "status": "operational",
    "it_load_mw": 52.0,
    "commissioned_year": 2020,
    "water_stressed": false,
    "notes": "Hiranandani Fortune City Panvel; 52MW; 7000 racks; Tier IV",
    "source": "https://colocation.yotta.com/data-center/"
  },
  {
    "id": "mh-navi-mumbai-yotta-nm2",
    "name": "Yotta NM2",
    "operator": "Yotta",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 18.989,
    "longitude": 73.118,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Same Panvel campus; core and shell ready",
    "source": "https://colocation.yotta.com/data-center/"
  },
  {
    "id": "up-greater-noida-yotta-d1",
    "name": "Yotta D1",
    "operator": "Yotta",
    "city": "Greater Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.4744,
    "longitude": 77.504,
    "status": "operational",
    "it_load_mw": 30.0,
    "commissioned_year": 2022,
    "water_stressed": true,
    "notes": "Delhi-NCR; ~30MW; 5000 racks; 300000 sq ft",
    "source": "https://colocation.yotta.com/data-center/yotta-d1-datacenter-ncr-delhi/"
  },
  {
    "id": "up-greater-noida-yotta-d2",
    "name": "Yotta D2",
    "operator": "Yotta",
    "city": "Greater Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.4744,
    "longitude": 77.504,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Part of 160MW 6-building park",
    "source": "https://www.datacenterdynamics.com/en/news/yotta-launches-data-center-in-noida-india/"
  },
  {
    "id": "up-greater-noida-yotta-d3",
    "name": "Yotta D3",
    "operator": "Yotta",
    "city": "Greater Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.4744,
    "longitude": 77.504,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Part of 160MW 6-building park",
    "source": "https://www.datacenterdynamics.com/en/news/yotta-launches-data-center-in-noida-india/"
  },
  {
    "id": "gj-gift-city-yotta-g1",
    "name": "Yotta G1",
    "operator": "Yotta",
    "city": "Gandhinagar",
    "state": "Gujarat",
    "latitude": 23.16,
    "longitude": 72.684,
    "status": "operational",
    "it_load_mw": 2.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "GIFT City; IFSC-compliant; ~2MW; 350 racks",
    "source": "https://yotta.com/press-releases/yottas-cloud-data-center-in-gift-city-gujarat-goes-live/"
  },
  {
    "id": "tn-chennai-yotta-dc1",
    "name": "Yotta Chennai",
    "operator": "Yotta",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "under_construction",
    "it_load_mw": 140.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Up to 140MW; 25000 racks",
    "source": "https://colocation.yotta.com/data-center/"
  },
  {
    "id": "mh-navi-mumbai-pdg-mu1",
    "name": "PDG MU1",
    "operator": "Princeton Digital Group",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.159,
    "longitude": 72.996,
    "status": "operational",
    "it_load_mw": 150.0,
    "commissioned_year": 2023,
    "water_stressed": false,
    "notes": "Airoli 50-acre park; first 50MW live; expanding to 150MW",
    "source": "https://princetondg.com/locations/india/"
  },
  {
    "id": "mh-navi-mumbai-pdg-mu2",
    "name": "PDG MU2",
    "operator": "Princeton Digital Group",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.159,
    "longitude": 72.996,
    "status": "under_construction",
    "it_load_mw": 120.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "10-acre site; 120MW; broke ground 2025-26",
    "source": "https://www.datacenterdynamics.com/en/news/pdg-plans-two-more-data-center-campuses-in-india-totaling-210mw/"
  },
  {
    "id": "tn-chennai-pdg-ch1",
    "name": "PDG CH1",
    "operator": "Princeton Digital Group",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "under_construction",
    "it_load_mw": 72.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "9.3-acre site; 72MW; part of USD 1B India expansion",
    "source": "https://www.datacenterdynamics.com/en/news/pdg-plans-two-more-data-center-campuses-in-india-totaling-210mw/"
  },
  {
    "id": "mh-navi-mumbai-bridge-bby01",
    "name": "Bridge Data Centres BBY01",
    "operator": "Bridge Data Centres",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.149,
    "longitude": 73.001,
    "status": "operational",
    "it_load_mw": 20.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Dighe; 350000 sq ft; 20MW; 16 data halls",
    "source": "https://www.bridgedc.com/"
  },
  {
    "id": "mh-navi-mumbai-capitaland-mumbai01",
    "name": "CapitaLand Data Centre Navi Mumbai 1",
    "operator": "CapitaLand / Ascendas",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.159,
    "longitude": 72.996,
    "status": "under_construction",
    "it_load_mw": 108.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Airoli; CLINT; 108MW; up to 575000 sq ft; LEED Gold target",
    "source": "https://www.capitaland.com/en/find-a-property/global-property-listing/data-centres/capitaland-s-datacentrenavimumbai1.html"
  },
  {
    "id": "tn-chennai-capitaland-dc1",
    "name": "CapitaLand Data Centre Chennai",
    "operator": "CapitaLand / Ascendas",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.114,
    "longitude": 80.162,
    "status": "under_construction",
    "it_load_mw": 54.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Ambattur; 54MW; ~USD 500M tech park",
    "source": "https://www.datacenterdynamics.com/en/news/capitaland-planning-more-data-centers-in-india-in-hyderabad-bengaluru-and-noida/"
  },
  {
    "id": "tg-hyderabad-capitaland-dc1",
    "name": "CapitaLand Data Centre Hyderabad",
    "operator": "CapitaLand / Ascendas",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.4239,
    "longitude": 78.3776,
    "status": "under_construction",
    "it_load_mw": 40.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "ITPH; 40MW; construction started",
    "source": "https://www.datacenterdynamics.com/en/news/capitaland-planning-more-data-centers-in-india-in-hyderabad-bengaluru-and-noida/"
  },
  {
    "id": "ka-bengaluru-capitaland-dc1",
    "name": "CapitaLand Data Centre Bengaluru",
    "operator": "CapitaLand / Ascendas",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.985,
    "longitude": 77.736,
    "status": "proposed",
    "it_load_mw": 42.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "ITPB; 42MW planned",
    "source": "https://www.datacenterdynamics.com/en/news/capitaland-planning-more-data-centers-in-india-in-hyderabad-bengaluru-and-noida/"
  },
  {
    "id": "mh-mumbai-aws-apsouth1",
    "name": "AWS Asia Pacific (Mumbai) ap-south-1",
    "operator": "Amazon AWS",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2016,
    "water_stressed": false,
    "notes": "ap-south-1 launched 2016; exact siting undisclosed, city centroid",
    "source": "https://aws.amazon.com/local/india/"
  },
  {
    "id": "tg-hyderabad-aws-apsouth2",
    "name": "AWS Asia Pacific (Hyderabad) ap-south-2",
    "operator": "Amazon AWS",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2022,
    "water_stressed": true,
    "notes": "ap-south-2 launched Nov 2022; exact siting undisclosed, city centroid",
    "source": "https://aws.amazon.com/blogs/aws/now-open-the-30th-aws-region-asia-pacific-hyderabad-region-in-india/"
  },
  {
    "id": "mh-mumbai-aws-investment",
    "name": "AWS Maharashtra cloud expansion",
    "operator": "Amazon AWS",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "AWS $8.3bn Maharashtra investment by 2030; siting undisclosed",
    "source": "https://www.aboutamazon.in/news/aws/aws-invests-8-billion-in-maharashtra"
  },
  {
    "id": "mh-pune-azure-centralindia",
    "name": "Azure Central India",
    "operator": "Microsoft Azure",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2015,
    "water_stressed": true,
    "notes": "Central India region (Pune) launched 2015; siting undisclosed, city centroid",
    "source": "https://news.microsoft.com/en-in/microsoft-launches-azure-availability-zones-in-its-central-india-datacenter-region/"
  },
  {
    "id": "mh-mumbai-azure-westindia",
    "name": "Azure West India",
    "operator": "Microsoft Azure",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2015,
    "water_stressed": false,
    "notes": "West India region (Mumbai) launched 2015; siting undisclosed, city centroid",
    "source": "https://learn.microsoft.com/en-us/azure/reliability/regions-list"
  },
  {
    "id": "tn-chennai-azure-southindia",
    "name": "Azure South India",
    "operator": "Microsoft Azure",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2015,
    "water_stressed": true,
    "notes": "South India region (Chennai) launched 2015; siting undisclosed, city centroid",
    "source": "https://learn.microsoft.com/en-us/azure/reliability/regions-list"
  },
  {
    "id": "tg-hyderabad-azure-region",
    "name": "Azure India datacenter region Hyderabad",
    "operator": "Microsoft Azure",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Hyderabad Azure region announced 2022; ~Rs16000cr; siting undisclosed",
    "source": "https://news.microsoft.com/en-in/microsoft-india-hyderabad-data-center-region-intent/"
  },
  {
    "id": "gj-jamnagar-azure-jioindiawest",
    "name": "Azure Jio India West",
    "operator": "Microsoft Azure / Jio",
    "city": "Jamnagar",
    "state": "Gujarat",
    "latitude": 22.4707,
    "longitude": 70.0577,
    "status": "operational",
    "it_load_mw": 7.5,
    "commissioned_year": 2021,
    "water_stressed": true,
    "notes": "Azure Jio India West operated by Jio in Jamnagar; ~7.5MW",
    "source": "https://www.datacenterdynamics.com/en/news/reliance-jio-partners-microsoft-will-build-azure-data-centers-across-india/"
  },
  {
    "id": "mh-mumbai-gcp-asiasouth1",
    "name": "Google Cloud Mumbai asia-south1",
    "operator": "Google Cloud",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2017,
    "water_stressed": false,
    "notes": "asia-south1 launched 2017; siting undisclosed, city centroid",
    "source": "https://cloud.google.com/about/locations"
  },
  {
    "id": "dl-delhi-gcp-asiasouth2",
    "name": "Google Cloud Delhi NCR asia-south2",
    "operator": "Google Cloud",
    "city": "Delhi NCR",
    "state": "Delhi",
    "latitude": 28.6139,
    "longitude": 77.209,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2021,
    "water_stressed": true,
    "notes": "asia-south2 launched Jul 2021; siting undisclosed, city centroid",
    "source": "https://cloud.google.com/blog/products/infrastructure/google-cloud-region-in-delhi-ncr-is-now-open"
  },
  {
    "id": "mh-mumbai-oci-region",
    "name": "Oracle Cloud Infrastructure Mumbai",
    "operator": "Oracle Cloud",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2019,
    "water_stressed": false,
    "notes": "OCI Mumbai region launched 2019; siting undisclosed, city centroid",
    "source": "https://www.oracle.com/in/cloud/public-cloud-regions/"
  },
  {
    "id": "tg-hyderabad-oci-region",
    "name": "Oracle Cloud Infrastructure Hyderabad",
    "operator": "Oracle Cloud",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2020,
    "water_stressed": true,
    "notes": "OCI Hyderabad region launched 2020; siting undisclosed, city centroid",
    "source": "https://www.oracle.com/in/corporate/pressrelease/oracle-opens-second-cloud-region-2020-06-29.html"
  },
  {
    "id": "ap-andhra-reliance-ai-twin",
    "name": "Reliance 1GW AI data center Andhra Pradesh",
    "operator": "Reliance/Jio",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "latitude": 17.6868,
    "longitude": 83.2185,
    "status": "proposed",
    "it_load_mw": 1000.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "1GW AI DC in AP announced as twin to Jamnagar; placed at Visakhapatnam centroid",
    "source": "https://www.business-standard.com/companies/news/reliance-andhra-pradesh-1gw-ai-data-centre-investment-125111401010_1.html"
  },
  {
    "id": "mh-mumbai-equinix-mb1",
    "name": "Equinix Mumbai MB1",
    "operator": "Equinix",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2021,
    "water_stressed": false,
    "notes": "Former GPX Mumbai 1 Tier IV; hosts 5 internet exchanges",
    "source": "https://www.equinix.com/data-centers/asia-pacific-colocation/india-colocation/mumbai-data-centers/mb1"
  },
  {
    "id": "mh-mumbai-equinix-mb2",
    "name": "Equinix Mumbai MB2",
    "operator": "Equinix",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": 16.0,
    "commissioned_year": 2021,
    "water_stressed": false,
    "notes": "Former GPX Mumbai 2 (16MW); Chandivali",
    "source": "https://www.equinix.com/data-centers/asia-pacific-colocation/india-colocation/mumbai-data-centers/mb2"
  },
  {
    "id": "mh-mumbai-equinix-mb3",
    "name": "Equinix Mumbai MB3",
    "operator": "Equinix",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2024,
    "water_stressed": false,
    "notes": "First self-built Equinix Mumbai IBX in Chandivali; up to 5475 cabinets",
    "source": "https://newsroom.equinix.com/Equinix-Invests-Over-86-Million-to-Build-Its-Third-Data-Center-in-Mumbai"
  },
  {
    "id": "tn-chennai-equinix-cn1",
    "name": "Equinix Chennai CN1",
    "operator": "Equinix",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2024,
    "water_stressed": true,
    "notes": "5.5-acre Chennai IBX interconnected with Mumbai MB3",
    "source": "https://www.business-standard.com/companies/news/equinix-opens-fourth-data-centre-mumbai-mb3-investment-126040801271_1.html"
  },
  {
    "id": "mp-indore-rackbank",
    "name": "RackBank Indore AI Data Center",
    "operator": "RackBank",
    "city": "Indore",
    "state": "Madhya Pradesh",
    "latitude": 22.7196,
    "longitude": 75.8577,
    "status": "under_construction",
    "it_load_mw": 80.0,
    "commissioned_year": 2025,
    "water_stressed": true,
    "notes": "India's first purpose-built AI DC; 80MW in four 20MW phases; immersion cooling",
    "source": "https://www.datacenterdynamics.com/en/news/rackbank-announces-80mw-madya-pradesh-data-center-in-india/"
  },
  {
    "id": "mh-navimumbai-lumina-airtrunk",
    "name": "AirTrunk BOM1 (Lumina) Airoli",
    "operator": "AirTrunk / Lumina CloudInfra",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1559,
    "longitude": 73.0169,
    "status": "under_construction",
    "it_load_mw": 60.0,
    "commissioned_year": 2025,
    "water_stressed": false,
    "notes": "Blackstone-backed Lumina campus Airoli; acquired by AirTrunk",
    "source": "https://www.datacenterdynamics.com/en/news/blackstone-backed-lumina-cloudinfra-breaks-ground-on-60mw-data-center-campus-in-navi-mumbai-india/"
  },
  {
    "id": "tn-chennai-digitalconnexion-maa10",
    "name": "Digital Connexion MAA10",
    "operator": "Digital Connexion",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.1143,
    "longitude": 80.1548,
    "status": "operational",
    "it_load_mw": 100.0,
    "commissioned_year": 2024,
    "water_stressed": true,
    "notes": "Reliance-Brookfield-Digital Realty JV; Ambattur; scalable to 100MW; Meta reported tenant",
    "source": "https://www.prnewswire.com/in/news-releases/digital-realty-launches-maa10-data-center-in-chennai-sets-new-standards-for-indias-data-center-industry-302033510.html"
  },
  {
    "id": "mh-mumbai-digitalconnexion",
    "name": "Digital Connexion Mumbai",
    "operator": "Digital Connexion",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.89,
    "status": "under_construction",
    "it_load_mw": 40.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "40MW Chandivali; Reliance-Brookfield-Digital Realty JV",
    "source": "https://www.datacenterdynamics.com/en/news/digital-connexion-to-launch-data-center-in-chennai-india/"
  },
  {
    "id": "dl-delhi-nic-ndc",
    "name": "NIC National Data Centre Delhi",
    "operator": "National Informatics Centre",
    "city": "New Delhi",
    "state": "Delhi",
    "latitude": 28.6139,
    "longitude": 77.209,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Government cloud DC; 1.6PB storage; e-governance",
    "source": "https://www.nic.gov.in/data-centres/"
  },
  {
    "id": "tg-hyderabad-nic-ndc",
    "name": "NIC National Data Centre Hyderabad",
    "operator": "National Informatics Centre",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Government cloud DC; ~106 racks",
    "source": "https://www.nic.gov.in/data-centres/"
  },
  {
    "id": "mh-pune-nic-ndc",
    "name": "NIC National Data Centre Pune",
    "operator": "National Informatics Centre",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Government cloud DC",
    "source": "https://www.nic.gov.in/data-centres/"
  },
  {
    "id": "od-bhubaneswar-nic-ndc",
    "name": "NIC National Data Centre Bhubaneswar",
    "operator": "National Informatics Centre",
    "city": "Bhubaneswar",
    "state": "Odisha",
    "latitude": 20.2961,
    "longitude": 85.8245,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2018,
    "water_stressed": false,
    "notes": "Cloud-enabled government DC since 2018",
    "source": "https://www.nic.gov.in/data-centres/"
  },
  {
    "id": "mh-navimumbai-neevcloud",
    "name": "NeevCloud AI Factory (planned)",
    "operator": "NeevCloud",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.033,
    "longitude": 73.0297,
    "status": "proposed",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Modular AI campuses 1MW-300MW+; targeting 40000 GPUs by 2026",
    "source": "https://www.neevcloud.com/ai-supercloud/"
  },
  {
    "id": "up-noida-e2e",
    "name": "E2E Networks Noida",
    "operator": "E2E Networks",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "latitude": 28.5355,
    "longitude": 77.391,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "GPU cloud DC; 1024 NVIDIA H200 cluster in Delhi NCR",
    "source": "https://analyticsindiamag.com/ai-news-updates/e2e-cloud-launches-nvidia-h200-gpu-clusters-in-delhi-ncr-and-chennai/"
  },
  {
    "id": "tn-chennai-e2e",
    "name": "E2E Networks Chennai",
    "operator": "E2E Networks",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2025,
    "water_stressed": true,
    "notes": "1024 NVIDIA B200/H200 GPU cluster; partnership with L&T",
    "source": "https://www.datacenterdynamics.com/en/news/e2e-networks-acquires-1024-nvidia-b200-gpu-cluster-for-chennai-data-center/"
  },
  {
    "id": "mh-navimumbai-lt-panvel",
    "name": "L&T Cloudfiniti Panvel",
    "operator": "L&T (Cloudfiniti)",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 18.9894,
    "longitude": 73.1175,
    "status": "operational",
    "it_load_mw": 2.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "2MW operational; part of L&T 150MW-by-2027 plan",
    "source": "https://india.entrepreneur.com/technology/lt-cloudfiniti-aims-to-scale-up-data-center-capacity-to-90/490311"
  },
  {
    "id": "mh-navimumbai-lt-mahape",
    "name": "L&T Cloudfiniti Mahape",
    "operator": "L&T (Cloudfiniti)",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.1075,
    "longitude": 73.0166,
    "status": "under_construction",
    "it_load_mw": 50.0,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Two buildings of 25MW each at Mahape",
    "source": "https://india.entrepreneur.com/technology/lt-cloudfiniti-aims-to-scale-up-data-center-capacity-to-90/490311"
  },
  {
    "id": "ka-bengaluru-lt-whitefield",
    "name": "L&T Cloudfiniti Whitefield",
    "operator": "L&T (Cloudfiniti)",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9698,
    "longitude": 77.75,
    "status": "proposed",
    "it_load_mw": 40.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "40MW campus in feasibility",
    "source": "https://india.entrepreneur.com/technology/lt-cloudfiniti-aims-to-scale-up-data-center-capacity-to-90/490311"
  },
  {
    "id": "mh-nashik-esds",
    "name": "ESDS Nashik DC",
    "operator": "ESDS",
    "city": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.9975,
    "longitude": 73.7898,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Satpur MIDC HQ; Tier III",
    "source": "https://www.esds.co.in/our-datacenter"
  },
  {
    "id": "mh-navimumbai-esds-airoli",
    "name": "ESDS Navi Mumbai (Airoli) DC",
    "operator": "ESDS",
    "city": "Navi Mumbai",
    "state": "Maharashtra",
    "latitude": 19.156,
    "longitude": 73.009,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Reliable Tech Park Airoli; Tier III",
    "source": "https://www.esds.co.in/our-datacenter"
  },
  {
    "id": "ka-bengaluru-esds",
    "name": "ESDS Bengaluru DC",
    "operator": "ESDS",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.845,
    "longitude": 77.661,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Electronic City Phase-1; Tier III",
    "source": "https://www.esds.co.in/our-datacenter"
  },
  {
    "id": "pb-mohali-esds",
    "name": "ESDS Mohali DC",
    "operator": "ESDS",
    "city": "Mohali",
    "state": "Punjab",
    "latitude": 30.7046,
    "longitude": 76.7179,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2022,
    "water_stressed": null,
    "notes": "80000 sq ft; Tier III; launched 2022",
    "source": "https://www.esds.co.in/data-center-at-mohali"
  },
  {
    "id": "ka-bengaluru-nxtgen-hddc",
    "name": "NxtGen HDDC Bengaluru",
    "operator": "NxtGen",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": 20.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "High Density Datacenter; up to 20MW; partly with BSNL",
    "source": "https://www.nxtgen.com/data-centers"
  },
  {
    "id": "mh-pune-tata-comm",
    "name": "Tata Communications Pune DC",
    "operator": "Tata Communications",
    "city": "Pune",
    "state": "Maharashtra",
    "latitude": 18.6298,
    "longitude": 73.8997,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Tata's largest Indian DC on Alandi Rd",
    "source": "https://www.tatacommunications.com/"
  },
  {
    "id": "rj-jaipur-everdata",
    "name": "Everdata Jaipur DC",
    "operator": "Everdata Technologies",
    "city": "Jaipur",
    "state": "Rajasthan",
    "latitude": 26.9124,
    "longitude": 75.7873,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "ISO 27001; BFSI; Gopalpura Bypass Rd",
    "source": "https://www.everdata.com/"
  },
  {
    "id": "rj-jaipur-serverwala",
    "name": "Serverwala Jaipur DC",
    "operator": "Serverwala Cloud Data Centers",
    "city": "Jaipur",
    "state": "Rajasthan",
    "latitude": 26.9124,
    "longitude": 75.7873,
    "status": "operational",
    "it_load_mw": 11.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "~11MW; HQ DC",
    "source": "https://www.serverwala.com/"
  },
  {
    "id": "ap-amaravati-pi",
    "name": "Pi Amaravati (Vijayawada)",
    "operator": "Pi Datacenters",
    "city": "Vijayawada",
    "state": "Andhra Pradesh",
    "latitude": 16.5062,
    "longitude": 80.648,
    "status": "operational",
    "it_load_mw": 60.0,
    "commissioned_year": 2016,
    "water_stressed": null,
    "notes": "Asia's largest Uptime Tier IV at launch; 500000 sqft; 60MW; up to 5000 racks",
    "source": "https://www.datacenterdynamics.com/en/news/pi-datacenters-gets-tier-iv-badge-for-facility-in-andhra-pradesh/"
  },
  {
    "id": "gj-ahmedabad-genx",
    "name": "GenX Cloud Ahmedabad (GIFT City)",
    "operator": "GenX Cloud",
    "city": "Gandhinagar",
    "state": "Gujarat",
    "latitude": 23.1645,
    "longitude": 72.6841,
    "status": "operational",
    "it_load_mw": 10.8,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "GIFT City; 1204 racks; 10.8MW",
    "source": "https://genxcloud.in/datacenter-ahmedabad/"
  },
  {
    "id": "gj-gandhinagar-ishan",
    "name": "Ishan Technologies Gandhinagar DC",
    "operator": "Ishan Technologies",
    "city": "Gandhinagar",
    "state": "Gujarat",
    "latitude": 23.2156,
    "longitude": 72.6369,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Tier III colocation in Infocity Gandhinagar",
    "source": "https://www.ishantechnologies.com/"
  },
  {
    "id": "ke-kochi-arideocean",
    "name": "Aride Ocean DC Kochi",
    "operator": "Aride Ocean Infoway",
    "city": "Kochi",
    "state": "Kerala",
    "latitude": 10.0476,
    "longitude": 76.3217,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": 2000,
    "water_stressed": false,
    "notes": "KINFRA Kalamassery; hosting since 2000",
    "source": "https://www.arideocean.com/"
  },
  {
    "id": "ke-kochi-dtsnet",
    "name": "DTS-NET India Kochi DC",
    "operator": "DTS-NET India",
    "city": "Kochi",
    "state": "Kerala",
    "latitude": 10.0476,
    "longitude": 76.3217,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Mamangalam Cochin",
    "source": "https://www.dts-net.com/"
  },
  {
    "id": "tn-coimbatore-servercake",
    "name": "ServerCake Coimbatore DC",
    "operator": "ServerCake",
    "city": "Coimbatore",
    "state": "Tamil Nadu",
    "latitude": 11.0168,
    "longitude": 76.9558,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "First DC in Coimbatore; rack colocation",
    "source": "https://servercake.in/"
  },
  {
    "id": "mh-nagpur-reliance-mauda",
    "name": "Reliance Data Center Nagpur (Mauda)",
    "operator": "Reliance Data Center",
    "city": "Nagpur",
    "state": "Maharashtra",
    "latitude": 21.1458,
    "longitude": 79.0882,
    "status": "operational",
    "it_load_mw": 7.5,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "IDC-1/IDC-2 at Mauda; ANSI/TIA-942-B; Jio-Azure site",
    "source": "https://cloudscene.com/data-center/india/regional/reliance-communications-reliance-data-center-nagpur"
  },
  {
    "id": "wb-kolkata-reliance",
    "name": "Reliance Kolkata Data Center",
    "operator": "Reliance Data Center",
    "city": "Kolkata",
    "state": "West Bengal",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "525000 sqft; ~Rs1000cr; Microsoft tie-up",
    "source": "https://baxtel.com/data-center/reliance-kolkata"
  },
  {
    "id": "gj-jamnagar-reliance",
    "name": "Reliance Jamnagar AI Data Center",
    "operator": "Reliance Industries",
    "city": "Jamnagar",
    "state": "Gujarat",
    "latitude": 22.4707,
    "longitude": 70.0577,
    "status": "under_construction",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Up to 3GW AI campus with green power; 120MW+ targeted H2 2026",
    "source": "https://www.lightreading.com/data-centers/india-s-reliance-is-building-massive-3gw-data-center-report"
  },
  {
    "id": "od-bhubaneswar-stpi",
    "name": "STPI Bhubaneswar Data Center",
    "operator": "Software Technology Parks of India",
    "city": "Bhubaneswar",
    "state": "Odisha",
    "latitude": 20.2961,
    "longitude": 85.8245,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Tier III standard; 7500 sqft; ~121 racks",
    "source": "https://bhubaneswar.stpi.in/en/data-center/bhubaneshwar"
  },
  {
    "id": "as-guwahati-stpi",
    "name": "STPI Guwahati Data Center",
    "operator": "Software Technology Parks of India",
    "city": "Guwahati",
    "state": "Assam",
    "latitude": 26.1445,
    "longitude": 91.7362,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "7000 sqft; ~97 commercial racks",
    "source": "https://guwahati.stpi.in/en/directorate-data-centers"
  },
  {
    "id": "tg-hyderabad-blackstone",
    "name": "Blackstone Hyderabad Data Center",
    "operator": "Blackstone",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "proposed",
    "it_load_mw": 150.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "150MW; ~Rs4500cr; MoU at WEF Davos 2025",
    "source": "https://w.media/blackstone-tillman-global-holdings-and-ursa-clusters-to-build-data-centers-in-telangana/"
  },
  {
    "id": "tg-hyderabad-ursaclusters",
    "name": "Ursa Clusters Hyderabad Data Center",
    "operator": "Ursa Clusters",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "proposed",
    "it_load_mw": 100.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "100MW AI hub; ~Rs5000cr; MoU 2025",
    "source": "https://w.media/blackstone-tillman-global-holdings-and-ursa-clusters-to-build-data-centers-in-telangana/"
  },
  {
    "id": "tg-hyderabad-tillman",
    "name": "Tillman Global Hyderabad Data Center",
    "operator": "Tillman Global Holdings",
    "city": "Hyderabad",
    "state": "Telangana",
    "latitude": 17.385,
    "longitude": 78.4867,
    "status": "proposed",
    "it_load_mw": 300.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "300MW; ~Rs15000cr; MoU 2025",
    "source": "https://www.deccanchronicle.com/southern-states/telangana/telangana-signs-mou-with-tillman-global-holdings-for-data-center-in-hyderabad-1856155"
  },
  {
    "id": "ka-bengaluru-krutrim",
    "name": "Krutrim AI Data Center Bengaluru",
    "operator": "Krutrim (Ola)",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "status": "operational",
    "it_load_mw": 20.0,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Sovereign AI GPU cloud; ~20MW scaling to 1GW by 2028",
    "source": "https://www.datacenterdynamics.com/en/news/indias-krutrim-plans-three-chips-and-1gw-cloud-expansion-from-2026/"
  },
  {
    "id": "mh-mumbai-neysa",
    "name": "Neysa AI Cloud Mumbai",
    "operator": "Neysa Networks",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.076,
    "longitude": 72.8777,
    "status": "operational",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Mumbai-based AI acceleration cloud; 20000+ GPUs planned",
    "source": "https://neysa.ai/"
  },
  {
    "id": "tg-mekaguda-community",
    "name": "Mekaguda residents' petition",
    "operator": "Community report",
    "city": "Mekaguda",
    "state": "Telangana",
    "latitude": 17.2,
    "longitude": 78.1,
    "status": "community_reported",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "56 residents petitioned the High Court alleging waste dumping in Tungakunta Lake near a data-centre site",
    "source": "https://restofworld.org/2024/microsoft-data-center-india-mekaguda-industrial-waste/"
  },
  {
    "id": "ap-vizag-hrf-community",
    "name": "Vizag HRF objection (Google-Adani hub)",
    "operator": "Community report",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "latitude": 17.82,
    "longitude": 83.37,
    "status": "community_reported",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Human Rights Forum demanded a halt, citing a forest NOC near Kambalakonda eco-sensitive zone and acute water stress",
    "source": "https://www.thenewsminute.com/andhra-pradesh/hrf-challenges-legality-of-adani-google-vizag-data-centre-demands-immediate-stop"
  },
  {
    "id": "ka-yamare-community",
    "name": "Yamare villagers — groundwater report",
    "operator": "Community report",
    "city": "Bengaluru",
    "state": "Karnataka",
    "latitude": 12.93,
    "longitude": 77.78,
    "status": "community_reported",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": true,
    "notes": "Panchayat reports groundwater for eight villages now available only at 100 feet as data centres expand",
    "source": "https://www.downtoearth.org.in/science-technology/indias-digital-thirst-what-data-centre-giants-arent-saying-about-their-water-use"
  },
  {
    "id": "mh-chandivali-community",
    "name": "Chandivali families — generator pollution",
    "operator": "Community report",
    "city": "Mumbai",
    "state": "Maharashtra",
    "latitude": 19.11,
    "longitude": 72.892,
    "status": "community_reported",
    "it_load_mw": null,
    "commissioned_year": null,
    "water_stressed": false,
    "notes": "Residents report persistent diesel-generator pollution; CSTEP flags gensets as a regional air-pollution source",
    "source": "https://earthjournalism.net/stories/its-hell-for-us-here-mumbai-families-suffer-as-data-centers-keep-the-city-hooked-on-coal-in"
  }
];
