// Community-impact reporting and national statistics, scraped from published sources.
// Each story carries a verbatim/paraphrased claim, attribution, source URL, location and theme.
window.IMPACT_STATS = [
  { stat: "India's operational data-centre capacity quadrupled in five years", value: "0.4 GW (2020) → ~1.5 GW (2025)", attribution: "Press Information Bureau, via Mongabay India", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", theme: "energy" },
  { stat: "Projected capacity growth by 2030", value: "~1.4 GW → ~9 GW", attribution: "IEEFA", url: "https://ieefa.org/resources/indias-power-hungry-data-centre-sector-crossroads", theme: "energy" },
  { stat: "Data-centre share of India's electricity", value: "~0.5% (2024) → >2× by 2030", attribution: "CEEW with SYSTEMIQ", url: "https://www.ceew.in/publications/how-is-data-centre-infrastructure-in-india-shaping-power-and-water-use", theme: "energy" },
  { stat: "Longer-run electricity share", value: "<1% now → ~3% by 2030", attribution: "IEEFA", url: "https://ieefa.org/resources/indias-power-hungry-data-centre-sector-crossroads", theme: "energy" },
  { stat: "Annual data-centre water consumption", value: "~150 → 358 billion litres by 2030", attribution: "Mordor Intelligence, via Reccessary (CEEW corroborates baseline)", url: "https://www.reccessary.com/en/news/india-ai-data-center-water-crisis", theme: "water" },
  { stat: "Share of data centres in water-stressed regions", value: ">50%", attribution: "WRI India mapping, via Mongabay India", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", theme: "water" },
  { stat: "New builds since 2022 sited in water-stressed regions", value: "~2 in 3", attribution: "Bloomberg, via Reccessary", url: "https://www.reccessary.com/en/news/india-ai-data-center-water-crisis", theme: "water" },
  { stat: "Data-centre investment commitments 2019–2025", value: "~USD 94 billion", attribution: "Cushman & Wakefield", url: "https://www.cushmanwakefield.com/en/india/insights/india-data-centre-update", theme: "policy" },
  { stat: "Typical India PUE / WUE ranges", value: "PUE 1.0–2.0 · WUE 0–2.5 L/kWh", attribution: "CEEW, via Mongabay India", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", theme: "energy" },
  { stat: "State DC policies with any sustainability parameters", value: "5 of 15", attribution: "CEEW, via Reccessary", url: "https://www.reccessary.com/en/news/india-ai-data-center-water-crisis", theme: "policy" },
  { stat: "India e-waste generated FY2024–25", value: "~1.4 million tonnes", attribution: "Central Pollution Control Board (CPCB)", url: "https://www.uniindia.com/~/over-13-97-lakh-tonnes-e-waste-generated-in-2024-25-cpcb-data/Parliament/news/3542425.html", theme: "all" },
  { stat: "A single 100 MW facility's water draw", value: "~2 million litres / day", attribution: "Reccessary", url: "https://www.reccessary.com/en/news/india-ai-data-center-water-crisis", theme: "water" }
];

window.IMPACT_STORIES = [
  { quote: "A recent map by WRI India showed that more than half of India's data centres are located in water-stressed regions.", attribution: "Mongabay India — Priyanka Shankar, May 2026", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", location: "India", theme: "water" },
  { quote: "We filed an RTI with TRAI asking about the environmental impacts of data centres. It was forwarded to MeitY, which said it has zero information about data centres.", attribution: "Indumugi C., Internet Freedom Foundation — Mongabay India", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", location: "India", theme: "disclosure" },
  { quote: "Visakhapatnam district has the lowest groundwater available in the state — 2.12 TMC as of April 1, 2026.", attribution: "Mongabay India — May 2026", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", location: "Visakhapatnam, Andhra Pradesh", theme: "water" },
  { quote: "We don't know the source of water for the data centre. It is not mentioned in the EC. Even the amount of water required for cooling is not mentioned.", attribution: "Gutta Rohith, Human Rights Forum — Mongabay India", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/", location: "Visakhapatnam, Andhra Pradesh", theme: "disclosure" },
  { quote: "The Google-Adani Vizag data-centre environmental clearance was granted in a rushed manner — applications filed April 9, cleared April 18 — leaving little time for appraisal.", attribution: "E.A.S. Sarma (retd. IAS) — The News Minute, Apr 2026", url: "https://www.thenewsminute.com/andhra-pradesh/vizag-google-adani-ai-data-centre-state-govt-rushed-environmental-clearance-activists-allege", location: "Visakhapatnam, Andhra Pradesh", theme: "policy" },
  { quote: "The clearance acknowledges nearly 90% of the project site falls under the Pedda Chukka Konda Reserve Forest, but overrules it citing a topo sheet showing no forest.", attribution: "The News Minute — Apr 2026", url: "https://www.thenewsminute.com/andhra-pradesh/vizag-google-adani-ai-data-centre-state-govt-rushed-environmental-clearance-activists-allege", location: "Visakhapatnam, Andhra Pradesh", theme: "land" },
  { quote: "The Human Rights Forum demanded an immediate halt to the Vizag Hyperscale Data Centre, criticising the Forest NOC for the 160-acre project near Kambalakonda Wildlife Sanctuary's eco-sensitive zone.", attribution: "The News Minute — May 2026", url: "https://www.thenewsminute.com/andhra-pradesh/hrf-challenges-legality-of-adani-google-vizag-data-centre-demands-immediate-stop", location: "Visakhapatnam, Andhra Pradesh", theme: "protest" },
  { quote: "Spanning 480 acres across Tarluvada, Adavivaram, Mudasarlova and Rambilli for a 1 GW cluster, the project 'represents a looming environmental and economic disaster' in a water-stressed city.", attribution: "Human Rights Forum — The News Minute, Oct 2025", url: "https://www.thenewsminute.com/andhra-pradesh/hrf-calls-vizag-google-adani-data-centre-a-looming-environmental-disaster", location: "Visakhapatnam, Andhra Pradesh", theme: "protest" },
  { quote: "The Andhra government refused an RTI seeking the Google data-centre MoU, citing Sections 11 and 8(1)(d); five of eight State Information Commission posts lie vacant.", attribution: "Deccan Herald — Dec 2025", url: "https://www.deccanherald.com/india/andhra-pradesh/andhra-govt-refuses-to-disclose-google-data-centre-mou-3822194", location: "Andhra Pradesh", theme: "disclosure" },
  { quote: "Instagram restricted HRF posts critical of the Google-Adani data centre, citing the IT Act; at least 20 videos from 11 accounts were blocked in one week.", attribution: "The South First — Jun 2026", url: "https://thesouthfirst.com/andhrapradesh/instagram-restricts-hrf-posts-critical-of-google-adani-data-centre-projects-in-visakhapatnam/", location: "Visakhapatnam, Andhra Pradesh", theme: "disclosure" },
  { quote: "Google's Andhra deal includes tax exemptions, land, discounted tariffs and water/power reimbursements worth ₹22,002 crore (~$2.4 billion) over 20 years.", attribution: "Rest of World — Ananya Bhattacharya, Apr 2026", url: "https://restofworld.org/2026/india-data-center-tax-holiday-farmer-protests-ai/", location: "Andhra Pradesh", theme: "policy" },
  { quote: "'Governments are looking at this as an investment issue, rather than a political-economy concern,' as farmers said they were pressured to give up land amid protests.", attribution: "Rest of World — Apr 2026", url: "https://restofworld.org/2026/india-data-center-tax-holiday-farmer-protests-ai/", location: "India", theme: "land" },
  { quote: "'These big companies think they can enter small villages like ours, take our land, and destroy it,' said the village head, after 56 residents petitioned the High Court over alleged waste dumping in Tungakunta Lake.", attribution: "Rest of World — Aug 2024", url: "https://restofworld.org/2024/microsoft-data-center-india-mekaguda-industrial-waste/", location: "Mekaguda, Telangana", theme: "land" },
  { quote: "The Mekaguda conflict over a 21.6-acre data-centre site affected 57 households and 273 people, with residents alleging polluted groundwater across five villages and blocked farm cart-ways.", attribution: "Land Conflict Watch", url: "https://www.landconflictwatch.org/conflicts/data-centre-and-dispossession-land-livelihoods-and-environmental-concerns-in-mekaguda-telangana", location: "Mekaguda, Rangareddy, Telangana", theme: "land" },
  { quote: "With coal still dominant, large data centres effectively run on coal with no disclosure obligation; Maharashtra draws 78% and Delhi NCR 85–90% of power from fossil sources.", attribution: "The Wire Science — Gunjan Jena", url: "https://science.thewire.in/economy/energy/hidden-environmental-costs-india-data-centre-push/", location: "Maharashtra / Delhi NCR", theme: "energy" },
  { quote: "There is no law requiring disclosure of water consumption by data centres in India; Maharashtra alone hosts more than 40% of installed capacity.", attribution: "The Wire Science — Gunjan Jena", url: "https://science.thewire.in/economy/energy/hidden-environmental-costs-india-data-centre-push/", location: "India / Maharashtra", theme: "disclosure" },
  { quote: "A CSTEP report flagged diesel generators as a major regional air-pollution source; Amazon's Mumbai colocation centres bought 41 diesel gensets and seek to install more.", attribution: "Earth Journalism Network", url: "https://earthjournalism.net/stories/its-hell-for-us-here-mumbai-families-suffer-as-data-centers-keep-the-city-hooked-on-coal-in", location: "Mumbai, Maharashtra", theme: "noise" },
  { quote: "Nxtra by Airtel disclosed 216,357 kilolitres of water use in 2025 — 9,876 KL from groundwater and 191,152 KL bought from third parties — a rare voluntary disclosure.", attribution: "Down To Earth — Rohini Krishnamurthy, Nov 2025", url: "https://www.downtoearth.org.in/science-technology/indias-digital-thirst-what-data-centre-giants-arent-saying-about-their-water-use", location: "India", theme: "disclosure" },
  { quote: "'If a data centre causes depletion in Whitefield, that cannot be offset by restoring a lake elsewhere. It's an ineffective approach.'", attribution: "Labanya Prakash Jena, IEEFA — Down To Earth", url: "https://www.downtoearth.org.in/science-technology/indias-digital-thirst-what-data-centre-giants-arent-saying-about-their-water-use", location: "Bengaluru, Karnataka", theme: "water" },
  { quote: "'We supply groundwater to eight villages, including Yamare, but levels are falling. Water is now available only at 100 feet.'", attribution: "Praveen Kumar, Panchayat Development Officer — Down To Earth", url: "https://www.downtoearth.org.in/science-technology/indias-digital-thirst-what-data-centre-giants-arent-saying-about-their-water-use", location: "Bengaluru (peri-urban), Karnataka", theme: "water" },
  { quote: "Developers must declare a water source when applying, but once cleared, no agency verifies whether the declared source matches actual practice.", attribution: "Newslaundry / The News Minute — Apr 2026", url: "https://www.newslaundry.com/2026/04/16/in-bengalurus-water-stressed-areas-sit-most-of-its-data-centres", location: "Bengaluru, Karnataka", theme: "disclosure" },
  { quote: "Devanahalli, where newer data centres are pushing in, already consumes 169% of its permissible groundwater limit; Bengaluru extracts almost 10× what it recharges yearly.", attribution: "Newslaundry / The News Minute — Apr 2026", url: "https://www.newslaundry.com/2026/04/16/in-bengalurus-water-stressed-areas-sit-most-of-its-data-centres", location: "Bengaluru, Karnataka", theme: "water" },
  { quote: "Data centres are classified as 'essential services' in Maharashtra and Telangana, giving them prioritised water and power even during scarcity, over residents' needs.", attribution: "Deccan Chronicle — Archana Prasad, May 2026", url: "https://www.deccanchronicle.com/nation/current-affairs/indias-ai-data-centres-and-the-invisible-groundwater-cost-1959255", location: "Maharashtra & Telangana", theme: "policy" },
  { quote: "In Hyderabad IT hubs like Gachibowli, groundwater dropped nearly a metre in three months in early 2026; Telangana's average sits 7.72 m below ground.", attribution: "Deccan Chronicle — Archana Prasad, May 2026", url: "https://www.deccanchronicle.com/nation/current-affairs/indias-ai-data-centres-and-the-invisible-groundwater-cost-1959255", location: "Hyderabad, Telangana", theme: "water" }
];
