// Community / civic response to data centers in India — policy, regulatory, legal,
// transparency, rights, and mobilization action — and the organisations doing the work.
// Every item is sourced. cat ∈ policy|regulatory|legal|transparency|rights|mobilization
window.RESPONSE_ACTIONS = [
  // — Policy & incentives —
  { cat: "policy", title: "Telangana declares data centres an 'essential service'", location: "Telangana", summary: "The state's Data Centres Policy classifies DC firms as an essential service, exempting them from statutory power cuts and from the state Pollution Control Act and inspections — prioritising uptime over environmental oversight.", attribution: "Govt. of Telangana — 2024", url: "https://invest.telangana.gov.in/wp-content/uploads/2024/07/Telangana-Data-Centres-Policy-1.pdf" },
  { cat: "policy", title: "Maharashtra policy: essential service, power perks, no water safeguards", location: "Maharashtra", summary: "Maharashtra's IT/ITeS Policy 2023 gives data centres infrastructure status, electricity-duty exemption, a tariff subsidy and relaxed zoning even in no-development zones — but specifies no water-allocation or environmental conditions.", attribution: "Tech Policy Press — Dec 2025", url: "https://www.techpolicy.press/mumbais-data-center-dreams-run-on-coal-and-inequality/" },
  { cat: "policy", title: "UP Data Centre Policy 2021: dual-grid power, duty waivers", location: "Uttar Pradesh", summary: "UP guarantees uninterrupted dual-grid power (the state bearing one grid's cost for the first eight parks), a 10-year electricity-duty exemption and wheeling-charge waivers — with no comparable water-stewardship conditions.", attribution: "Invest UP — 2021", url: "https://invest.up.gov.in/wp-content/uploads/2021/09/DC-Policy-2021-Eng-final_page-f.pdf" },
  { cat: "policy", title: "Karnataka reviewing its 'water and energy guzzling' DC policy", location: "Karnataka", summary: "IT/BT Minister Priyank Kharge told the Assembly each MW of data centre needs ~25 million litres of water a year, and said Karnataka is preparing a 'sustainable data centre policy'. The Pollution Control Board has no consolidated cooling-water accounting.", attribution: "Deccan Herald — Mar 2026", url: "https://www.deccanherald.com/india/karnataka/karnataka-reviewing-policy-on-water-energy-guzzling-data-centres-3927531" },
  { cat: "policy", title: "CEEW: state DC policies lack PUE/WUE and water standards", location: "India", summary: "CEEW finds a water-governance deficit, an absence of PUE/WUE or carbon benchmarks, and weak climate-resilience framing across India's state data-centre policies — even as annual DC water use heads from ~150 billion litres (2025) to double by 2030.", attribution: "CEEW — 2026", url: "https://www.ceew.in/publications/how-is-data-centre-infrastructure-in-india-shaping-power-and-water-use" },

  // — Regulatory & clearances —
  { cat: "regulatory", title: "SEIAA cleared the 1 GW Vizag data centre in ~10 days, no EIA or hearing", location: "Andhra Pradesh", summary: "Andhra's SEIAA granted environmental clearance to the 1 GW Vizag Mega Data Centre Park on 18 Apr 2026, ~10 days after the application. Classified Category B2 'building/construction', it skipped any EIA and public hearing; the EC discloses no operational water use.", attribution: "Mongabay India — May 2026", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/" },
  { cat: "regulatory", title: "In India a data centre can be built with no environmental assessment", location: "India", summary: "'Data centre' appears nowhere in the EIA Notification 2006 schedule; clearance triggers only above 20,000 sq m as a 'building'. So a 300 MW hyperscale facility's energy, carbon, water and e-waste footprint is never formally assessed — unlike coal plants, which face public hearings.", attribution: "Decode / BOOM — Feb 2026", url: "https://www.decodeinternet.in/decode/interview-in-india-a-data-centre-can-be-built-without-any-environmental-assessment-30754" },
  { cat: "regulatory", title: "Greater Noida's data-centre corridor 'running on empty wells'", location: "Uttar Pradesh", summary: "Gautam Buddh Nagar now hosts 17 operational/upcoming data centres in a critically over-exploited groundwater block; reporting found facilities projected to consume billions of litres a year as approvals were streamlined without water-impact scrutiny.", attribution: "Earth Journalism Network — 2026", url: "https://earthjournalism.net/stories/a-booming-data-center-corridor-in-indias-uttar-pradesh-is-running-on-empty-wells" },

  // — Legal action —
  { cat: "legal", title: "57 farmers petition Telangana HC over Mekaguda lake pollution", location: "Mekaguda, Telangana", summary: "In July 2023, 57 Mekaguda farmers filed a PIL in the Telangana High Court alleging encroachment and dumping of industrial waste into the Tungakunta government lake near a Microsoft data-centre site, polluting groundwater across five villages affecting ~20,000 residents.", attribution: "The Hans India — Jul 2023", url: "https://www.thehansindia.com/news/cities/hyderabad/57-farmers-approach-hc-against-mnc-pharma-co-for-polluting-tungakunta-811984" },
  { cat: "legal", title: "Court rejects residents' bid to halt the Mekaguda data centre", location: "Mekaguda, Telangana", summary: "56 residents sued Microsoft and 35 other entities over alleged illegal land occupation and waste dumping. In 2023 a judge rejected their request to stop construction pending the case, calling it 'vague'; the full hearing remains pending.", attribution: "Rest of World — 2024", url: "https://restofworld.org/2024/microsoft-data-center-india-mekaguda-industrial-waste/" },
  { cat: "legal", title: "HRF challenges the Adani-Google Vizag clearance", location: "Visakhapatnam, Andhra Pradesh", summary: "The Human Rights Forum challenged the Forest NOC for the 160-acre hyperscale project near Kambalakonda Wildlife Sanctuary's eco-sensitive zone, demanding reclassification from Category B2 to A for full appraisal and criminal charges over alleged illegal forest clearing.", attribution: "The News Minute — May 2026", url: "https://www.thenewsminute.com/andhra-pradesh/hrf-challenges-legality-of-adani-google-vizag-data-centre-demands-immediate-stop" },
  { cat: "legal", title: "APSEIAA forest clearance for the Vizag DC faces challenge", location: "Visakhapatnam, Andhra Pradesh", summary: "HRF and others contest the SEIAA clearance, arguing the site's proximity to the Kambalakonda eco-sensitive zone triggers the General Condition under the EIA Notification 2006, requiring Category A appraisal rather than the granted B2.", attribution: "Countercurrents — Apr 2026", url: "https://countercurrents.org/2026/04/apseiaa-approval-for-google-adani-data-centre-in-reserve-forest-faces-legal-and-regulatory-challenge/" },

  // — Transparency & RTI —
  { cat: "transparency", title: "RTI to TRAI forwarded to MeitY, which had 'zero information'", location: "India", summary: "The Internet Freedom Foundation filed an RTI on data-centre environmental impacts with TRAI; it was forwarded to MeitY, which replied it had 'zero information about data centres' — despite MeitY having drafted the (un-notified) 2020 National Data Centre Policy.", attribution: "Mongabay India — May 2026", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/" },
  { cat: "transparency", title: "Andhra refuses to disclose the Google data-centre MoU", location: "Andhra Pradesh", summary: "The AP ITE&C department refused an RTI for its MoU with Google for the $15bn Vizag AI hub, invoking Sections 11 and 8(1)(d). Campaigners note the State Information Commission lacks a Chief Commissioner to even hear the appeal.", attribution: "Deccan Herald — 2026", url: "https://www.deccanherald.com/india/andhra-pradesh/andhra-govt-refuses-to-disclose-google-data-centre-mou-3822194" },

  // — Rights & free speech —
  { cat: "rights", title: "Instagram restricts HRF posts critical of the Vizag data centre", location: "Visakhapatnam, Andhra Pradesh", summary: "Instagram restricted HRF posts citing Section 79(3)(b) of the IT Act; HRF said ~20 videos from 11 accounts were blocked in a week, including an Environmental Reporting Collective investigation — which HRF called suppression of democratic scrutiny.", attribution: "The South First — Jun 2026", url: "https://thesouthfirst.com/andhrapradesh/instagram-restricts-hrf-posts-critical-of-google-adani-data-centre-projects-in-visakhapatnam/" },
  { cat: "rights", title: "AP police seek to restrict HRF social-media posts", location: "Andhra Pradesh", summary: "Guntur Urban police asked X, Instagram and Facebook to restrict HRF posts sharing a petition against the Vizag project, citing Section 79(3)(b) and the 2021 Intermediary Rules. HRF urged the government to 'desist from censorship'.", attribution: "The News Minute — Jun 2026", url: "https://www.thenewsminute.com/andhra-pradesh/ap-govt-seeks-to-restrict-hrf-social-media-posts-against-google-adani-data-centre" },

  // — Petitions & mobilization —
  { cat: "mobilization", title: "HRF demands an immediate halt to the Vizag hyperscale data centre", location: "Visakhapatnam, Andhra Pradesh", summary: "The Human Rights Forum demanded site works stop on the Google-Adani project over the forest NOC, eco-sensitive-zone proximity and acute groundwater stress, urging public consultation and full disclosure.", attribution: "Countercurrents — May 2026", url: "https://countercurrents.org/2026/05/hrf-demands-halt-to-vizag-hyperscale-data-center-over-alleged-environmental-violations/" },
  { cat: "mobilization", title: "Farmer backlash to Google (AP) and Microsoft (TG) data centres", location: "Andhra Pradesh & Telangana", summary: "Farmers near Google's Andhra project and Microsoft's Telangana site say they were pressured to surrender land through opaque land-pooling and kept out of allocation decisions, even as the state offers large tax incentives. Resistance continues at construction sites.", attribution: "Rest of World — Apr 2026", url: "https://restofworld.org/2026/india-data-center-tax-holiday-farmer-protests-ai/" },
  { cat: "mobilization", title: "Bhogapuram farmers oppose Reliance data-centre land acquisition", location: "Bhogapuram, Vizianagaram, AP", summary: "Farmers of Polipalli, Bhogapuram and nearby villages asked the government to withdraw the acquisition of 855 acres assigned to Reliance for a data centre and cable-landing station — now an obstacle to the project.", attribution: "Webnewswire — May 2026", url: "https://www.webnewswire.com/2026/05/25/govt-deals-with-obstacle-over-land-acquisition-for-reliance-data-centre-steel-plant/" },
  { cat: "mobilization", title: "Devanahalli village squeezed by data-centre water grants", location: "Devanahalli, Karnataka", summary: "In groundwater-depleted Devanahalli, the 250-person village of Akkalenahalli Mallenahalli faces a data centre allotted 650 kilolitres/day — water equal to the needs of 5,000 people — despite extraction already at 169% of the permissible limit.", attribution: "Down To Earth — 2026", url: "https://www.downtoearth.org.in/science-technology/indias-digital-thirst-how-bengalurus-tech-dreams-are-colliding-with-a-worsening-water-crisis" }
];

window.PARTNERS = [
  { name: "Human Rights Forum (HRF)", role: "Andhra civil-rights group leading opposition to the Google-Adani Vizag hyperscale data centres — petitions, legal challenges, and public alerts on water, forest and clearance violations.", type: "civil-society", url: "https://humanrightsforum.org/" },
  { name: "Internet Freedom Foundation (IFF)", role: "Digital-rights group; filed the RTI on data-centre environmental impact and published a 2026 explainer on India's data-centre policy gaps.", type: "civil-society", url: "https://internetfreedom.in/explainer-how-is-india-approaching-data-centers/" },
  { name: "Land Conflict Watch", role: "Researcher network documenting India's land conflicts; profiled the Mekaguda, Telangana data-centre dispossession and lake-pollution case.", type: "research", url: "https://www.landconflictwatch.org/conflicts/data-centre-and-dispossession-land-livelihoods-and-environmental-concerns-in-mekaguda-telangana" },
  { name: "Digital Empowerment Foundation (DEF)", role: "Investigated land allocation for data centres in Telangana, finding farmers and local bodies were kept out of decisions.", type: "civil-society", url: "https://www.defindia.org/" },
  { name: "WRI India", role: "Mapped India's data centres, showing more than half sit in water-stressed regions.", type: "research", url: "https://wri-india.org/" },
  { name: "CEEW", role: "Analyses how data-centre infrastructure shapes India's power and water use; flags missing PUE/WUE standards and recommends benchmarks.", type: "research", url: "https://www.ceew.in/publications/how-is-data-centre-infrastructure-in-india-shaping-power-and-water-use" },
  { name: "IEEFA", role: "Energy-finance institute; reports on powering India's AI data centres with renewables and the water-offset problem.", type: "research", url: "https://ieefa.org/resources/blue-seas-and-green-electrons-powering-indias-ai-data-centres" },
  { name: "CSTEP", role: "Bengaluru think tank researching climate, energy, water and AI policy relevant to data-centre siting and sustainability.", type: "research", url: "https://cstep.in/" },
  { name: "The Reporters' Collective", role: "Investigative newsroom reporting on government accountability and corporate incentives, including India's data-centre tax breaks.", type: "media", url: "https://www.reporters-collective.in/" },
  { name: "Mongabay India", role: "Environmental newsroom reporting on data-centre water and energy concerns and water-stressed siting across India.", type: "media", url: "https://india.mongabay.com/2026/05/india-bets-on-data-centres-even-as-water-energy-use-concerns-mount/" },
  { name: "Down To Earth", role: "Environmental publication covering Bengaluru's water crisis and data centres straining scarce groundwater.", type: "media", url: "https://www.downtoearth.org.in/science-technology/indias-digital-thirst-how-bengalurus-tech-dreams-are-colliding-with-a-worsening-water-crisis" },
  { name: "Earth Journalism Network", role: "Supports reporting on data-centre water use and its collision with India's water crisis.", type: "media", url: "https://earthjournalism.net/stories/what-data-center-giants-arent-saying-about-their-water-use-in-india" }
];
